baseURL = "/"
languageCode = "en-us"
title = "Alo誰s Micard | Tech blog"
theme = "terminal"
disqusShortname = "creekorful-me"
googleAnalytics = "UA-100732589-2"
disableAliases = true

[params]
  fullWidthTheme = false
  centerTheme = true
  themeColor = "green"

[permalinks]
  posts = "/:year/:month/:filename/"

[languages]
  [languages.en]
    languageName = "English"
    title = "Alo誰s Micard"
    subtitle = "Tech Blog"
    owner = "Alo誰s Micard"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Alo誰s Micard | Tech blog"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "github"
        name = "Github"
        url = "https://github.com/creekorful"
      [[languages.en.menu.main]]
        identifier = "linkedin"
        name = "Linkedin"
        url = "https://www.linkedin.com/in/creekorful"
      [[languages.en.menu.main]]
        identifier = "500px"
        name = "500px"
        url = "https://500px.com/creekorful"
      [[languages.en.menu.main]]
        identifier = "gaia-rocket-program"
        name = "Gaia Rocket Program"
        url = "https://www.gaiarocketprogram.fr"
      [[languages.en.menu.main]]
        identifier = "website"
        name = "Website"
        url = "https://creekorful.dev"
