baseURL = "https://blog-beta.creekorful.com"
languageCode = "en-us"
title = "Alo誰s Micard | Tech blog"
theme = "terminal"

[params]
  fullWidthTheme = false
  centerTheme = true
  themeColor = "blue"

[languages]
  [languages.en]
    languageName = "English"
    title = "Alo誰s Micard"
    subtitle = "Tech Blog"
    owner = "Alo誰s Micard"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Alo誰s Micard | Tech blog"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
